export const CONFIG = {
  defaultBranch: "master",

  defaultRepos: [
    "training.web",
    "crm.web",
    "portal.web",
    "bridge-admin.web",
    "marketing.web",
    "store.web",
    "task-manager",
    "document-manager.web",
    "pdp-gateway.web",
    "messenger",
    "simulators.web",
    "pilotage",
    "taxation",
  ],

  // Mapping des repos vers des noms courts pour les en-têtes CSV
  repoDisplayNames: {
    "training.web": "Training",
    "crm.web": "CRM",
    "portal.web": "Portal",
    "bridge-admin.web": "Admin",
    "marketing.web": "Marketing",
    "store.web": "Store",
    "task-manager": "Tasks",
    "document-manager.web": "Document",
    "pdp-gateway.web": "PA",
    messenger: "Messenger",
    "simulators.web": "Simulateur",
    pilotage: "Pilotage",
    taxation: "Assistant de TVA",
  },

  // Chemin vers le package.json dans chaque repo
  repoPackageJsonPaths: {
    "training.web": "package.json",
    "crm.web": "package.json",
    "portal.web": "package.json",
    "bridge-admin.web": "package.json",
    "marketing.web": "package.json",
    "store.web": "package.json",
    "task-manager": "package.json",
    "document-manager.web": "package.json",
    "pdp-gateway.web": "package.json",
    messenger: "package.json",
    "simulators.web": "package.json",
    pilotage: "front-end/package.json",
    taxation: "front-end/package.json",
  },

  github: {
    org: "fulll",
    apiBase: "https://api.github.com",
  },

  npm: {
    registryBase: "https://registry.npmjs.org",
    githubPackagesBase: "https://npm.pkg.github.com",
  },

  output: {
    defaultCsvHeaders: ["Package", "Latest"],
  },

  // Liste des packages @fulll archivés - génèrent des alertes spéciales
  archivedPackages: [
    "animate",
    "badge",
    "button",
    "calc",
    "cell-table",
    "checkbox",
    "color",
    "comment",
    "date",
    "dialog",
    "drawer",
    "drop-zone",
    "dropdown",
    "event",
    "helpkit",
    "icon",
    "list-select",
    "login",
    "masonreact",
    "mission",
    "mui-helpers",
    "nav-card",
    "pagination",
    "pdf",
    "polyfill",
    "popover",
    "preview",
    "radio",
    "react-enhanced-form",
    "react-free-dom",
    "react-select-user",
    "react-select",
    "rest",
    "row",
    "search-bar",
    "select-company",
    "snack-bar",
    "switch",
    "tag",
    "task",
    "textfield",
    "thumb",
    "tree-select",
    "ui-action-button",
    "ui-announcement",
    "ui-auth",
    "ui-avatar",
    "ui-badge",
    "ui-banner",
    "ui-breadcrumbs",
    "ui-button",
    "ui-card",
    "ui-checkbox",
    "ui-chip",
    "ui-collapse",
    "ui-colorpicker",
    "ui-core",
    "ui-datatable",
    "ui-datepicker",
    "ui-dialog",
    "ui-drawer",
    "ui-dropzone",
    "ui-ellipsis",
    "ui-file",
    "ui-filter-panel",
    "ui-icon-button",
    "ui-icon",
    "ui-keynumber",
    "ui-list-select",
    "ui-list",
    "ui-menu",
    "ui-modal",
    "ui-monthpicker",
    "ui-overlay",
    "ui-panel",
    "ui-progress",
    "ui-radio",
    "ui-select",
    "ui-skeleton",
    "ui-slider",
    "ui-snackbar",
    "ui-stepper",
    "ui-surface",
    "ui-switch",
    "ui-tab",
    "ui-table",
    "ui-task-card",
    "ui-textfield",
    "ui-theme-fulll",
    "ui-theme-ibiza-blueberry",
    "ui-theme-ibiza",
    "ui-theme-ied",
    "ui-toolbar",
    "ui-tooltip",
    "ui-topbar",
  ],
} as const;

export type Config = {
  branch: string;
  outputFile: string;
  interactive: boolean;
  repos: string[];
};
